name: Fuel Market Report

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:

  generate-report:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Emadeb Agent
        run: |
          python main.py

      - name: Commit Report
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add report.json

          git commit -m "Update report" || echo "No changes"

          git push
